#!/bin/sh
#-
# Copyright (c) 2017 Alexandre Joannou
# Copyright (c) 2018 Alex Richardson
# All rights reserved.
#
# This software was developed by SRI International and the University of
# Cambridge Computer Laboratory under DARPA/AFRL contract FA8750-10-C-0237
# ("CTSRD"), as part of the DARPA CRASH research programme.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
# 1. Redistributions of source code must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
# 2. Redistributions in binary form must reproduce the above copyright
#    notice, this list of conditions and the following disclaimer in the
#    documentation and/or other materials provided with the distribution.
#
# THIS SOFTWARE IS PROVIDED BY THE AUTHOR AND CONTRIBUTORS ``AS IS'' AND
# ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED.  IN NO EVENT SHALL THE AUTHOR OR CONTRIBUTORS BE LIABLE
# FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
# DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
# OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
# HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
# LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
# OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
# SUCH DAMAGE.
#

echo "Setting polling user_frac to 99"
/sbin/sysctl kern.polling.user_frac=99

echo "mount / rw"
/sbin/mount -o rw /

MDSZ=300m
echo "create $MDSZ TMPFS at /tmp"
mkdir -p /tmp
mount -t tmpfs -o size=$MDSZ tmpfs /tmp

if /sbin/ifconfig -l | grep atse0; then
    echo "set atse0 if to polling"
    /sbin/ifconfig atse0 polling

    echo "run dhclient on atse0"
    /sbin/dhclient atse0
fi
if /sbin/ifconfig -l | grep le0; then
    echo "set le0"
    /sbin/ifconfig le0

    echo "run dhclient on le0"
    /sbin/dhclient le0
fi

echo "set up loopback"
/sbin/ifconfig lo0 inet 127.0.0.1 up

BENCHDIR=/tmp/benchdir
mkdir $BENCHDIR
chmod 777 $BENCHDIR

echo "generate host keys"
for alg in rsa ecdsa ed25519 ; do
    keyfile="/etc/ssh/ssh_host_${alg}_key"
    if [ ! -e "$keyfile" ]; then
        ssh-keygen -t $alg -f "$keyfile" -N ""
    fi
    # ssh-keygen -l -f "$keyfile.pub"
done

echo "start sshd"
/usr/sbin/sshd

echo "Turn off CHERI unaligned access logging"
/sbin/sysctl machdep.unaligned_log_pps_limit=0

echo "exec /bin/sh"
exec /bin/sh
